import img1 from "../assets/new-product 2.png"
import img2 from "../assets/page4SEO.png"
import img3 from "../assets/page4Email.png"
import img4 from "../assets/page4Sound.png"
import img5 from "../assets/page4SocialMedia.png"
import img6 from "../assets/page4Content.png"

const PAGE_FOUR_DATA = [
    {
        img: img1,
        heading: "Sales Funnel",
        para: "Before we start with the genuine improvement of an item, a decent item procedure should initially be written down."
    },
    {
        img: img2,
        heading: "SEO",
        para: "To delineate your vision and objectives as plainly as could really be expected, we start the coordinated."
    },
    {
        img: img3,
        heading: "Email Marketing",
        para: "When there is a reasonable image of the end result, we can get everything rolling with the UX, the specialized."
    },
    {
        img: img4,
        heading: "Advertisement",
        para: "Once in a while suppositions made in the idea stage are hazardous to the point that it very well may be valuable."
    },
    {
        img: img5,
        heading: "Social Media",
        para: "A MVP , or Least Suitable Item, is the most straightforward variant of your item with which you can really offer."
    },
    {
        img: img6,
        heading: "Content Creation",
        para: "There’s no one way to run a data function. But today’s winning companies are able to equip their internal."
    }
]
export default PAGE_FOUR_DATA;